/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3066.0) */

#include "ble_scps.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside Scan Parameters packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside Scan Parameters packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_SCAN_INTERVAL_WINDOW_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Scan Interval Window. */ 
#define MAX_SCAN_REFRESH_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Scan Refresh. */ 

/**@brief Function for encoding Scan Interval Window.
 *
 * @param[in]   p_scan_interval_window              Scan Interval Window characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t scan_interval_window_encode(ble_scps_scan_interval_window_t * p_scan_interval_window, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint16_encode(&p_scan_interval_window->le_scan_interval, &encoded_buffer[len]); 
    len += bds_uint16_encode(&p_scan_interval_window->le_scan_window, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for decoding Scan Interval Window.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t scan_interval_window_decode(uint8_t data_len, uint8_t * p_data, ble_scps_scan_interval_window_t * p_write_val)
{
    uint8_t pos = 0;
    pos += bds_uint16_decode((data_len-pos), &p_data[pos], &p_write_val->le_scan_interval); 
    pos += bds_uint16_decode((data_len-pos), &p_data[pos], &p_write_val->le_scan_window); 

    return pos;
} 
/**@brief Function for encoding Scan Refresh Value.
 *
 * @param[in]   p_scan_refresh_value              Scan Refresh Value structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t scan_refresh_scan_refresh_value_encode(scan_refresh_scan_refresh_value_t * p_scan_refresh_value, uint8_t * encoded_buffer)
{
    uint8_t scan_refresh_value;
    scan_refresh_value = p_scan_refresh_value->scan_refresh_value;
    encoded_buffer[0] = scan_refresh_value;
    return 1; 
}

/**@brief Function for encoding Scan Refresh.
 *
 * @param[in]   p_scan_refresh              Scan Refresh characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t scan_refresh_encode(ble_scps_scan_refresh_t * p_scan_refresh, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += scan_refresh_scan_refresh_value_encode(&p_scan_refresh->scan_refresh_value, &encoded_buffer[len]); 
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_scps       Scan Parameters Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_scps_t * p_scps, ble_evt_t * p_ble_evt)
{
    p_scps->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_scps       Scan Parameters Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_scps_t * p_scps, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_scps->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_scps       Scan Parameters Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_scps_t * p_scps, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_scps->scan_interval_window_handles.value_handle)
    {
        if(p_scps->evt_handler != NULL)
        {
            ble_scps_evt_t evt;
            evt.evt_type = BLE_SCPS_SCAN_INTERVAL_WINDOW_EVT_WRITE;
            scan_interval_window_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.scan_interval_window);
            p_scps->evt_handler(p_scps, &evt);
        }
    }
    if(p_ble_evt->handle == p_scps->scan_refresh_handles.cccd_handle)
    {
        if(p_scps->evt_handler != NULL)
        {
            ble_scps_evt_t evt;
            evt.evt_type = BLE_SCPS_SCAN_REFRESH_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_scps->evt_handler(p_scps, &evt);
        }
    } 
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_scps_t * p_scps, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_scps       Scan Parameters Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_scps_on_ble_evt(ble_scps_t * p_scps, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_scps, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_scps, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_scps, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_scps, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the Scan Parameters. */
uint32_t ble_scps_init(ble_scps_t * p_scps, const ble_scps_init_t * p_scps_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_scps->evt_handler = p_scps_init->evt_handler;
    p_scps->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    BLE_UUID_BLE_ASSIGN(ble_uuid, 0x1813);
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_scps->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Scan Interval Window characteristic
    ble_scps_scan_interval_window_t scan_interval_window_initial_value = p_scps_init->ble_scps_scan_interval_window_initial_value; 

    uint8_t scan_interval_window_encoded_value[MAX_SCAN_INTERVAL_WINDOW_LEN];
    ble_add_char_params_t add_scan_interval_window_params;
    memset(&add_scan_interval_window_params, 0, sizeof(add_scan_interval_window_params));
    
    add_scan_interval_window_params.uuid                = 0x2A4F; 
    add_scan_interval_window_params.max_len             = MAX_SCAN_INTERVAL_WINDOW_LEN;
    add_scan_interval_window_params.init_len            = scan_interval_window_encode(&scan_interval_window_initial_value, scan_interval_window_encoded_value);
    add_scan_interval_window_params.p_init_value        = scan_interval_window_encoded_value; 
    add_scan_interval_window_params.char_props.write_wo_resp    = 1; 
    add_scan_interval_window_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_scan_interval_window_params.is_var_len          = 1; 

    err_code = characteristic_add(p_scps->service_handle, &add_scan_interval_window_params, &(p_scps->scan_interval_window_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Scan Refresh characteristic
    ble_scps_scan_refresh_t scan_refresh_initial_value = p_scps_init->ble_scps_scan_refresh_initial_value; 

    uint8_t scan_refresh_encoded_value[MAX_SCAN_REFRESH_LEN];
    ble_add_char_params_t add_scan_refresh_params;
    memset(&add_scan_refresh_params, 0, sizeof(add_scan_refresh_params));
    
    add_scan_refresh_params.uuid                = 0x2A31; 
    add_scan_refresh_params.max_len             = MAX_SCAN_REFRESH_LEN;
    add_scan_refresh_params.init_len            = scan_refresh_encode(&scan_refresh_initial_value, scan_refresh_encoded_value);
    add_scan_refresh_params.p_init_value        = scan_refresh_encoded_value; 
    add_scan_refresh_params.char_props.notify   = 1; 
    add_scan_refresh_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_scan_refresh_params.is_var_len          = 1; 

    err_code = characteristic_add(p_scps->service_handle, &add_scan_refresh_params, &(p_scps->scan_refresh_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for sending the Scan Refresh. */
uint32_t ble_scps_scan_refresh_send(ble_scps_t * p_scps, ble_scps_scan_refresh_t * p_scan_refresh)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_scps->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_SCAN_REFRESH_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = scan_refresh_encode(p_scan_refresh, encoded_value);
        hvx_params.handle = p_scps->scan_refresh_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_scps->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

